# arb-dir: assets\i18n
# template-arb-file: app_en.arb
# synthetic-package: false
# output-dir: lib\generated
# output-localization-file: app_localizations.dart
# output-class: AppLocalizations
# nullable-getter: false
